In [1]:
import numpy as np

from sklearn.metrics import pairwise_distances

In [14]:
X = np.random.rand(100,3)

In [33]:
cluster_idx = [1,10,99]
clusters = X[cluster_idx]
dist_matrix = pairwise_distances(X, clusters, metric="euclidean")
print(dist_matrix[:3, :])
dist = np.min(dist_matrix, axis=1).reshape(-1,1)
print(dist)

[[0.50830124 0.33824964 0.72535344]
 [0.         0.64481824 0.5393352 ]
 [0.84741938 0.48531369 0.74405171]]
[[0.33824964]
 [0.        ]
 [0.48531369]
 [0.54669418]
 [0.35092745]
 [0.44949971]
 [0.11436107]
 [0.34244913]
 [0.43171525]
 [0.59650185]
 [0.        ]
 [0.33458241]
 [0.56587618]
 [0.20744381]
 [0.26496342]
 [0.72019326]
 [0.44540278]
 [0.55280121]
 [0.53578771]
 [0.51339719]
 [0.59609057]
 [0.32329185]
 [0.79076591]
 [0.18644637]
 [0.59936766]
 [0.72376015]
 [0.21281686]
 [0.30595607]
 [0.0934908 ]
 [0.59003742]
 [0.33648141]
 [0.31185139]
 [0.2984669 ]
 [0.54276696]
 [0.38986137]
 [0.15376481]
 [0.48789494]
 [0.42948114]
 [0.12831363]
 [0.50848181]
 [0.13184483]
 [0.43457413]
 [0.40759165]
 [0.56313858]
 [0.33483663]
 [0.57514555]
 [0.22322318]
 [0.38975712]
 [0.38566485]
 [0.36203369]
 [0.1323897 ]
 [0.4065932 ]
 [0.5027366 ]
 [0.1056329 ]
 [0.40588977]
 [0.4191491 ]
 [0.34297999]
 [0.30896958]
 [0.54167772]
 [0.28574211]
 [0.20358647]
 [0.26596325]
 [0.32522818]
 [0.45739

In [21]:
random_distance = np.random.rand(100,1)
print(random_distance[:3, :])

[[0.5643997 ]
 [0.25702107]
 [0.40455323]]


In [26]:
distance = np.minimum(random_distance, dist_matrix)
print(distance)

[[5.08301243e-01 3.38249636e-01 5.64399698e-01]
 [0.00000000e+00 2.57021068e-01 2.57021068e-01]
 [4.04553230e-01 4.04553230e-01 4.04553230e-01]
 [8.28483272e-01 5.46694176e-01 8.28483272e-01]
 [1.94089652e-01 1.94089652e-01 1.94089652e-01]
 [4.49499707e-01 6.51158703e-01 6.39478553e-01]
 [3.04057282e-01 3.04057282e-01 1.14361069e-01]
 [4.39398446e-01 3.42449128e-01 6.34174442e-01]
 [6.38300446e-01 4.31715246e-01 8.69860087e-01]
 [9.56821827e-01 5.96501851e-01 8.23544146e-01]
 [6.44818244e-01 0.00000000e+00 6.61707038e-01]
 [4.47731225e-01 4.47731225e-01 3.34582409e-01]
 [1.54219768e-01 1.54219768e-01 1.54219768e-01]
 [4.48351795e-01 2.07443806e-01 4.48351795e-01]
 [7.09149549e-01 2.64963423e-01 6.61986233e-01]
 [3.66320154e-01 3.66320154e-01 3.66320154e-01]
 [1.34819024e-01 1.34819024e-01 1.34819024e-01]
 [5.18733318e-01 5.18733318e-01 5.18733318e-01]
 [6.32854834e-01 5.35787707e-01 6.32854834e-01]
 [5.66087177e-01 5.13397186e-01 5.66087177e-01]
 [1.47418175e-02 1.47418175e-02 1.474181